spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/other?characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
      max-active: 10
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-wait: 5000000

#spring.datasource.url=jdbc:mysql://localhost/other
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver